# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
# test
name: Build an deploy

on:
  push:
    branches:
      - 'release-v*'
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - name: Set Version
      if: startsWith(github.ref, 'refs/heads/release-v')
      run: |
        export VERSION_NUMBER=$(echo ${GITHUB_REF} | cut -d'v' -f 2).${GITHUB_RUN_NUMBER}
        echo "VERSION " $VERSION_NUMBER
        sed -i -e 's/0\.0\.0/'"$VERSION_NUMBER"'/g' setup.py
        echo "VERSION " $VERSION_NUMBER
    - name: Install
      run: |
        python setup.py install
    - name: Create egg
      run: |
        python setup.py sdist
    - name: Release
      uses: pypa/gh-action-pypi-publish@release/v1
      if: startsWith(github.ref, 'refs/heads/release-v')
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        verbose: true